[build-system]
requires = [
    "pip >= 21.3.1",
    "requests >= 2.28.1",
    "setuptools >= 59.6.0",
    "setuptools_scm >= 6.4.2",
    "wheel >= 0.37.1",
    "Cython >= 0.29.32"
]
build-backend = "setuptools.build_meta"